Controllers/InformatikaiTanfolyamokController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_WH.App_Code.Database;
namespace MVC_WH.Controllers
{
    public class InformatikaiTanfolyamokController : Controller
    {
        // GET: InformatikaiTanfolyamok
        [AllowAnonymous]
        public ActionResult InformatikaiTanfolyamok()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Csharp_Programozo_Tanfolyam()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Csharp_Programozo_Tanfolyam40()
        {
            return View();
        }

        

        public ActionResult AspNet_wwebpogramozo_tanfolyam()
        {
            return View();
        }

        public ActionResult kezdo_linux_tanfolyam()
        {
            return View();
        }

        public ActionResult php_webprogramozo_tanfolyam()
        {
            return View();
        }

        public ActionResult jelentkezes_informatikai_tanfolyamra()
        {
          /*  List<SelectListItem> BirthDates = new List<SelectListItem>();

            for (int i = 1950; i < 2002; i++)
            {
                BirthDates.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            }
            
            ViewBag.irthDateList = BirthDates;
            */
            return View();
        }

        public ActionResult office_irodai_tanfolyam()
        {
            return View();
        }
        

        public ActionResult JelentkezoForm()
        {
            string courseID = Request.Form["courseID"];
            string FullName = Request.Form["FullName"];
            string Email = Request.Form["Email"];

            string GDPR = Request.Form["TermsAndConditions"];
            bool isGDPR = false;
            if (GDPR == "true,false")
            {
                isGDPR = true;
            }

            if (isGDPR)
            {
                GDPR = "elfogadva";
            }
            else GDPR = "nem jo";


            string AccountAddress = Request.Form["UjSzamlazasiCim"];
            bool isAccountAddress = false;
            if (AccountAddress == "on")
            {
                isAccountAddress = true;
            }


            string birthYear = Request.Form["szulEv"];
            string birthMonth = Request.Form["szulHonap"];
            string birthDay = Request.Form["szulNap"];

            string CustomBirthDate = getCustomBirtdateFormat(birthYear,birthMonth,birthDay);
            string BirthCity = Request.Form["PlaceCity"];
            string BirthCountry = Request.Form["placecountry"];
            string Address =  Request.Form["Address"];

            string HighestEducation = Request.Form["HighestEducation"];
            string Telephone = Request.Form["TelephoneNumber"];
            
            string OtherComment = Request.Form["Megjegyzes"];



            try
            {
                if (isAccountAddress)
                {
                    string BillingName = Request.Form["SzamlazasiNev"];
                    string BillingAddress = Request.Form["SzamlazasiCim"];
                    string TaxNumber = Request.Form["TaxNumber"];
                    EducationDatabaseSQL.setNewApplier(courseID, FullName, Email, CustomBirthDate, BirthCity, Address, BirthCountry, HighestEducation, OtherComment, Telephone, BillingName, BillingAddress, TaxNumber);
                }
                else
                {

                    EducationDatabaseSQL.setNewApplier(courseID, FullName, Email, CustomBirthDate, BirthCity, Address, BirthCountry, HighestEducation, OtherComment, Telephone);
                }
            }
            catch (Exception)
            {

                throw;
            }
            finally {
                EducationDatabaseSQL.CloseDB();
            }

           

           
            return View("jelentkezes_informatikai_tanfolyamra");
        }



        /*
         *                        PRIVATE METHODS      PRIVATE METHODS             PRIVATE METHODS
         */
         /// <summary>
         /// Visszatér egy szuletesi ido stringgel
         /// </summary>
         /// <returns></returns>
        private string getCustomBirtdateFormat(string ev,string ho,string nap)
        {
            return ev + "." + ho + "." + nap;
        }


        /*
         *                       PRIVATE METHODS END     PRIVATE METHODS END    PRIVATE METHODS END
         * 
         */
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Workinghunter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquerynew")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    <div id="fb-root"></div>
    <script>
(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/hu_HU/sdk.js#xfbml=1&version=v2.12&appId=544525502342038';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Workinghunter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_MenuPartial");
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="container-fluid">

        <footer class="row Footer" style="background-color: #ACACAC;">

            @Html.Partial("_TanfolyamFooter");
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Profile", "ProfileEdit", "Home")</li>
        <li>@Html.ActionLink("JobTarget", "JobTarget", "Home")</li>
        <li>@Html.ActionLink("Search", "Search", "Home")</li>
        <li>@Html.ActionLink("Statistics", "Statistics", "Home")</li>
    </ul>
}

Views/Shared/_TanfolyamFooter.cshtml
        <section class="col-sm-8">
            <ul class="list-inline list-unstyled">
                <li class="firstItem" style="margin-left: 3%;">Adatvédelmi nyilatkozat</li>
                <li>Süti politika</li>
                <li>Rólunk</li>
                <li>Moodle oktatási anyagok</li>
                <li><a target="_blank" href="http://www.smart-computers.eu">Szoftver- és webfejlesztés</a></li>
                <li>Álláskeresőknek</li>
                <li>Álláshirdetőknek</li>
                <li>Oktatás</li>
               <!-- <li>Janos Lakatos Production</li> --> 
              <li>Prisoftinno technologies s.r.o.</li>
            </ul>
        </section>

Views/Shared/_TanfolyamOldalsoMenu.cshtml
<section class="row">

        <h4 class="tanfolyamokH4">Tanfolyamok</h4>

</section>

<section class="row">
    <section id="it-tanfolyam-programozas-csharp-80" class="col-sm-12 curseTitle">
        <h5>@Html.ActionLink("C# programozó tanfolyam online + 80 gyakorlati óra", "Csharp_Programozo_Tanfolyam", "InformatikaiTanfolyamok")</h5>
    </section>
</section>

<section class="row">
    <section id="it-tanfolyam-programozas-csharp-40" class="col-sm-12 curseTitle">
        <h5><a href="http://workinghunter.com/informatikai-tanfolyamok/csharp-dotnet-programozas-tanfolyam-80.aspx">C# programozás online + 80 óra gyakorlat</a></h5>

    </section>
</section>

<section class="row">
    <section id="it-tanfolyam-webprogramozas-80" class="col-sm-12 curseTitle">
        <h5>@Html.ActionLink("ASP.NET webprogramozás online + 80 óra gyakorlat", "AspNet_wwebpogramozo_tanfolyam", "InformatikaiTanfolyamok")</h5>
    </section>
</section>

<section class="row">
    <section id="it-tanfolyam-cikk-php-programozas-80" class="col-sm-12 curseTitle">
        <h5>@Html.ActionLink("PHP programozás online + 80 óra gyakorlat", "php_webprogramozo_tanfolyam", "InformatikaiTanfolyamok")</h5>
    </section>
</section>

<section class="row">
    <section id="it-tanfolyam-cikk-php-rendszergazda-linux" class="col-sm-12 curseTitle">
        <h5>@Html.ActionLink("Linux rendszergazda tanfolyam", "kezdo_linux_tanfolyam", "InformatikaiTanfolyamok")</h5>

    </section>
</section>

<section class="row">
    <div class="fb-page" data-href="https://www.facebook.com/workinghuntermagyarorszag/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/workinghuntermagyarorszag/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/workinghuntermagyarorszag/">Workinghunter Magyarország</a></blockquote></div>


</section>


    