Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_WH.Models;
namespace MVC_WH.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TestProfile(ProfileEditModels model)
        {
            if (ModelState.IsValid)
            {
                //TODO: SubscribeUser(model.Email);
            }

            return View("ProfileEdit", model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }



        [Authorize]
        public ActionResult ProfileEdit()
        {
            ViewBag.Message = "Your profile edit page.";
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Action", Value = "0" });

            items.Add(new SelectListItem { Text = "Drama", Value = "1" });

            items.Add(new SelectListItem { Text = "Comedy", Value = "2", Selected = true });

            items.Add(new SelectListItem { Text = "Science Fiction", Value = "3" });

            ViewBag.MovieType = items;
            return View();
        }

        [Authorize]
        public ActionResult JobTarget()
        {
            ViewBag.Message = "Your job target page.";

            return View();
        }

        [Authorize]
        public ActionResult Statistics()
        {
            ViewBag.Message = "Your statistics page.";

            return View();
        }

        [Authorize]
        public ActionResult Search()
        {
            ViewBag.Message = "Your search page.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult InformatikaiTanfolyamok()
        {
            ViewBag.Message = "Your ssdfsdfch page.";
            return View();
        }

        

    }
}

Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using MVC_WH.Models;
using System.Threading.Tasks;
using System.Web.UI.WebControls;
using MVC_WH.App_Code.Database;
namespace MVC_WH.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult Index()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Action", Value = "0" });

            items.Add(new SelectListItem { Text = "Drama", Value = "1" });

            items.Add(new SelectListItem { Text = "Comedy", Value = "2", Selected = true });

            items.Add(new SelectListItem { Text = "Science Fiction", Value = "3" });

            ViewBag.MovieType = items;

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult TestProfile(ProfileEditModels model, JobEnum je)
        {
            if (ModelState.IsValid)
            {
                //TODO: SubscribeUser(model.Email);
            }


            // return View("~/Views/Home/ProfileEdit.cshtml");
            return RedirectToAction("ProfileEdit", "Home");
        }

        [HttpPost]
        public ActionResult UserProfilePictureUpload()
        {


            return RedirectToAction("ProfileEdit", "Home");
        }

        [HttpPost]
        public ActionResult BirthPlaceChange()
        {
            return RedirectToAction("Contact", "Home");
        }

        [HttpPost]
        public ActionResult CurrentPlaceChange()
        {
            return RedirectToAction("Contact", "Home");
        }

        [HttpPost]
        public ActionResult PhoneNumberChange()
        {
            return RedirectToAction("ProfileEdit", "Home");
        }

        [HttpPost]
        public ActionResult EmailContactChange()
        {
            return RedirectToAction("ProfileEdit", "Home");
        }

        public ActionResult FbUrlChange()
        {
            //mukodik! teszteltem
            string fb = Request.Form["newFbUrl"].ToString();
            string WorkerID = Request.Form["worker"].ToString();
            DatabaseSQL.UpdateFbUrl_Change(WorkerID, fb);
            DatabaseSQL.CloseDB();
            return RedirectToAction("ProfileEdit", "Home");
        }

        public ActionResult SelectCategory()
        {

            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Action", Value = "0" });

            items.Add(new SelectListItem { Text = "Drama", Value = "1" });

            items.Add(new SelectListItem { Text = "Comedy", Value = "2", Selected = true });

            items.Add(new SelectListItem { Text = "Science Fiction", Value = "3" });

            ViewBag.MovieType = items;

            return View();

        }


        [HttpPost]
        public  ActionResult SaveTarget()
        {


            return RedirectToAction("Contact", "Home");
        }


        /// <summary>
        /// Visszatér a városok listájával a viewba!
        /// </summary>
        /// <param name="countryID"></param>
        /// <returns></returns>
        [HttpPost]
        public string GetCities(int countryID)
        {
            // List<ListItem> items =  DatabaseSQL.GetCitiesList(countryID);
            //DatabaseSQL.CloseDB();
            string items = "jott az elem Teeee!";
            return items;
        }

    }
}

Views/Home/About.cshtml
@model MVC_WH.Models.ProfileEditModels

@{
    ViewBag.Title = "About";
//Minta, hogy a többit hogyan ell majd felépíteni! :D
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

@using (Html.BeginForm("TestProfile", "UserProfile", FormMethod.Post))
{
    @Html.LabelFor(model => model.TextToHtml)
    @Html.TextBoxFor(model => model.TextToHtml)
    @Html.ValidationMessageFor(model => model.TextToHtml)
    <button type="submit">Save</button>
}
 

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div>
    
    <img class="img-thumbnail" src="~/Content/Img/workinghunter-main-job-img.jpg" style="margin:0 auto;" />
    @Html.ActionLink("Regisztráció", "Register", "Account", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg regBtnPos" })
   
</div>

<div class="row">
    <div class="col-md-10">
        <h2>Válts, kezdj, építs Karriert!</h2>
        <p>
            Vadászd le, álmaid Állását! A Workinghunter új lehetőségeket biztosít Neked!
        </p>
       
    </div>
    <div class="col-md-2">
        <p><a class="btn btn-default " href="http://workinghunter.com/hu/Allaskeresoknek.aspx">Bővebben</a></p>
    </div>
</div>

<div class="row">
    <div class="col-md-10">
        <h2>Hirdetési lehetőség Vállalkozásoknak!</h2>
        <p>
            Hirdesd meg Állásajánlataidat a Workingunteren! Hirdess INGYEN!
        </p>

    </div>
    <div class="col-md-2">
        <p><a class="btn btn-default " href="http://workinghunter.com/hu/Munkaadoknak.aspx">Bővebben</a></p>
    </div>
</div>

<div class="row">
    <div class="col-md-10">
        <h2>Tanulj Nálunk! Légy Te is programozó!</h2>
        <p>
           Rengeteg gyakorlat orientált informatikai, programozó tanfolyammal várunk!
        </p>

    </div>
    <div class="col-md-2">
        <p><a class="btn btn-default " href="/InformatikaiTanfolyamok/InformatikaiTanfolyamok">Bővebben</a></p>
    </div>
</div>

Views/Home/JobTarget.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Job taerget</h1>

Views/Home/Search.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Keresés</h1>
<div class="container-fluid WHContent">


</div>

Views/Home/Statistics.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Statistics</h1>